# Generated by Django 5.0.4 on 2024-05-11 03:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="team",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("teamname", models.CharField(max_length=64)),
                ("description", models.CharField(max_length=128)),
                ("creationtime", models.DateTimeField(auto_now_add=True)),
                (
                    "admin",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="admin",
                        to="users.user",
                    ),
                ),
                (
                    "members",
                    models.ManyToManyField(
                        help_text="Select members for this team",
                        max_length=50,
                        to="users.user",
                    ),
                ),
            ],
        ),
    ]
