# Generated by Django 5.0.4 on 2024-05-11 05:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("teams", "0001_initial"),
        ("users", "0002_rename_name_user_name_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="team",
            old_name="teamname",
            new_name="Team_Name",
        ),
        migrations.RenameField(
            model_name="team",
            old_name="description",
            new_name="Team_description",
        ),
        migrations.RenameField(
            model_name="team",
            old_name="creationtime",
            new_name="created_at",
        ),
        migrations.AlterField(
            model_name="team",
            name="members",
            field=models.ManyToManyField(
                help_text="Select members for team", max_length=50, to="users.user"
            ),
        ),
    ]
