# Generated by Django 5.0.4 on 2024-05-11 03:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("teams", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Boardmodel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=64, unique=True)),
                ("description", models.CharField(max_length=128)),
                ("creationtime", models.DateTimeField(auto_now_add=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "open"),
                            ("inprogress", "inprogress"),
                            ("closed", "closed"),
                        ],
                        default="OPEN",
                        max_length=15,
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        help_text="Select team for this project",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="teams.team",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TaskModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=64, unique=True)),
                ("description", models.CharField(max_length=128)),
                ("creationtime", models.DateTimeField(auto_now_add=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "open"),
                            ("inprogress", "inprogress"),
                            ("complete", "complete"),
                        ],
                        default="OPEN",
                        max_length=15,
                    ),
                ),
                (
                    "user_id",
                    models.ForeignKey(
                        help_text="Select the team for the task",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="teams.team",
                    ),
                ),
            ],
        ),
    ]
