# Generated by Django 5.0.4 on 2024-05-11 05:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("teamboard", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="boardmodel",
            name="status",
            field=models.CharField(
                choices=[
                    ("Complete", "Complete"),
                    ("Active", "Active"),
                    ("Pending", "Pending"),
                ],
                default="OPEN",
                max_length=15,
            ),
        ),
        migrations.AlterField(
            model_name="taskmodel",
            name="status",
            field=models.CharField(
                choices=[
                    ("Complete", "Complete"),
                    ("Active", "Active"),
                    ("Pending", "Pending"),
                ],
                default="OPEN",
                max_length=15,
            ),
        ),
    ]
