# Generated by Django 5.0.4 on 2024-05-11 06:01

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("teamboard", "0002_alter_boardmodel_status_alter_taskmodel_status"),
    ]

    operations = [
        migrations.RenameField(
            model_name="boardmodel",
            old_name="description",
            new_name="Project_Description",
        ),
        migrations.RenameField(
            model_name="boardmodel",
            old_name="name",
            new_name="Project_name",
        ),
        migrations.RenameField(
            model_name="boardmodel",
            old_name="creationtime",
            new_name="created_at",
        ),
    ]
